### ISSUE TITLE
Intégrer le passthrough dans l’app et un script permettant la calibration de l’environnement virtuel

### ISSUE THREAD

**Issue by TiborUdvari** [fromageboum/head-md-folding-worlds#9]

**Comment by TiborUdvari** [comment]
Looks like it works with OpenXR as well https://forum.unity.com/threads/possible-to-make-the-oculus-passthrough-api-work-with-the-openxr-plugin.1412400/

**Comment by Aprobado** [comment]
I'm wondering if it wouldn't be easier to not use openxr. Do you have a feature that necessitates using openxr?

**Comment by Aprobado** [comment]
Nevermind, I managed to make the Passthrough work with OpenXR on my branch.

**Comment by TiborUdvari** [comment]
@Aprobado is it normal that I have this in play mode with the passthrough? Is there a way to simulate for dev?

![Uploading Screenshot 2023-10-24 at 19.51.34.png…]()
